#!/bin/bash
water_base="ewatr"
stir_base="ti.r"
bestchol_base="shteolc"
water_in_decimal=0
for (( i=0; i<${#WATER}; i++ )); do
    char="${WATER:$i:1}"
    water_in_decimal=$((water_in_decimal * ${#water_base} + $(expr index "$water_base" "$char" - 1)))
stir_in_decimal=0
for (( i=0; i<${#STIR}; i++ )); do
    char="${STIR:$i:1}"
    stir_in_decimal=$((stir_in_decimal * ${#stir_base} + $(expr index "$stir_base" "$char" - 1)))
result_in_decimal=$((water_in_decimal + stir_in_decimal))
result=""
while [ $result_in_decimal -gt 0 ]; do
    remainder=$((result_in_decimal % ${#bestchol_base}))
    result="${bestchol_base:$remainder:1}$result"
    result_in_decimal=$((result_in_decimal / ${#bestchol_base}))
echo "$result"
