#!/usr/bin/env bash
# Display a list of currently running processes
ps -e -o user,pid,%cpu,%mem,vsize,rss,tty,stat,lstart,time,args --sort=pid | awk '{printf "%-8s %-8s %-7s %-7s %-8s %-7s %-8s %-10s %-10s %-50s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, substr($10,1,50)}'
