#!/usr/bin/env bash
# Create a file to signal termination
while true; do
    echo "To infinity and beyond"
    sleep 1
      for signal in /tmp/stop_signal_*; do
        if [ -f "$signal" ]; then  # Corrected to use 'signal' instead of 'file'
            echo "Terminated"
            break 2
        fi
    done
done
