#!/usr/bin/env bash
# Find the PID of the '4-to_infinity_and_beyond' process
pid=$(pgrep -f 4-to_infinity_and_beyond)
# If the process exists, send a SIGTERM signal by writing to /proc/$pid/comm
if [ -n "$pid" ]; then
    echo "Terminating process with PID: $pid"
    echo -e "STOP" > /proc/"$pid"/comm
else
    echo "Process not found!"
fi
