#!/usr/bin/env bash
# Get the PID of the process named 4-to_infinity_and_beyond
PID=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$PID" ]; then
  
    echo "Terminating process $PID"
    echo "1" > /proc/"$PID"/oom_score_adj
else
    echo "No process found"
fi
