#!/usr/bin/env bash
# Find the PID of the '7-highlander' process
pid=$(pgrep -f 7-highlander)

# If the process exists, "kill" it by writing to /proc/$pid/comm
if [ -n "$pid" ]; then
    echo "Terminating process with PID: $pid"
    echo "STOP" > /proc/"$pid"/comm  # Writing "STOP" to terminate the process
else
    echo "Process not found!"
fi
