#!/usr/bin/env bash
# Find the PID of the '7-highlander' process using pgrep
pid=$(pgrep -f 7-highlander)
# If the process exists
if [ -n "$pid" ]; then
    # Kill the process
    kill -9 "$pid"
    echo "Killed process 7-highlander with PID: $pid"
else
    echo "No 7-highlander process found"
fi
