#!/usr/bin/env bash
# Find the PID of the '7-highlander' process
pid=$(pgrep -f 7-highlander) 

# If the process exists, send a SIGTERM signal
if [ -n "$pid" ]; then
    echo " "
    kill -TERM "$pid"  # This sends the TERM signal
else
    echo "Process not found!"
fi
